# Site
repository: ChanYeongShin/ChanYeongShin.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Eren Shin
title: Mondeique CTO / M.S Candidate for School of Integrated Technology in Yonsei Univ
email: eren@mondeique.com
website: https://github.com/ChanYeongShin

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: 
github_username:  ChanYeongShin
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/me.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hello, I'm Chan Yong Shin, working as a CTO for a startup called Mondeique. I like to develop quietly in a place where no one is around at dawn, 
  but I enjoy communicating with people at the same time. 
  MBTI goes back and forth between ENFJ and ENFP. 
  
  We are confident that future online shopping will be done through virtual fitting developed by our company.
  
  I am a full-stack AI developer who can develop Frontend IOS using Swift from backend server development.
  
  
  I am skilled at <mark>Python</mark> <mark>Tensorflow</mark> <mark>Pytorch</mark> <mark>Keras</mark> <mark>OpenCV</mark> <mark>Django</mark> <mark>Swift</mark> 
  <mark>MATLAB</mark> <mark>Docker</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Muli-View 3D avatar generate with PIFu
        link: github.com/ChanYeongShin
        # link_text: Project Website
        additional_links:
          - title:  ChanYeongShin/ChanYeongShin.github.io
            icon: fab fa-github
            url: github.com/ChanYeongShin/ChanYeongShin.github.io
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          test
        description: | # this will include new lines to allow paragraphs
          test
      - layout: top-middle
        title: Towards Photo-Realistic Virtual Try-On by Adaptively Generating↔Preserving Image Content (ACGPN)
        link: github.com/ChanYeongShin
        # link_text: Project Website
        additional_links:
          - title:  ChanYeongShin/ChanYeongShin.github.io
            icon: fab fa-github
            url: github.com/ChanYeongShin/ChanYeongShin.github.io
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          test
        description: | # this will include new lines to allow paragraphs
          test
      - layout: top-middle
        title: human-parser for generating segmentation map 
        link: github.com/ChanYeongShin
        # link_text: Project Website
        additional_links:
          - title:  ChanYeongShin/ChanYeongShin.github.io
            icon: fab fa-github
            url: github.com/ChanYeongShin/ChanYeongShin.github.io
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          test
        description: | # this will include new lines to allow paragraphs
          test
      - layout: top-middle
        title: Main Backend Server for app "SIIOT"
        link: github.com/ChanYeongShin
        # link_text: Project Website
        additional_links:
          - title:  ChanYeongShin/ChanYeongShin.github.io
            icon: fab fa-github
            url: github.com/ChanYeongShin/ChanYeongShin.github.io
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          test
        description: | # this will include new lines to allow paragraphs
          test
      - layout: top-middle
        title: Django-Channels Chat Server develop & deploy for app "SIIOT"
        link: github.com/ChanYeongShin
        # link_text: Project Website
        additional_links:
          - title:  ChanYeongShin/ChanYeongShin.github.io
            icon: fab fa-github
            url: github.com/ChanYeongShin/ChanYeongShin.github.io
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          test
        description: | # this will include new lines to allow paragraphs
          test
      - layout: top-middle
        title: MONDE-BENGAL - Web Crawling Server develop & deploy for app "SIIOT"
        link: github.com/ChanYeongShin
        # link_text: Project Website
        additional_links:
          - title:  ChanYeongShin/ChanYeongShin.github.io
            icon: fab fa-github
            url: github.com/ChanYeongShin/ChanYeongShin.github.io
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          test
        description: | # this will include new lines to allow paragraphs
          test
      - layout: top-middle
        title: IOS develop using SWIFT for app "PEPUP"
        link: github.com/ChanYeongShin
        # link_text: Project Website
        additional_links:
          - title:  ChanYeongShin/ChanYeongShin.github.io
            icon: fab fa-github
            url: github.com/ChanYeongShin/ChanYeongShin.github.io
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          test
        description: | # this will include new lines to allow paragraphs
          test
      - layout: top-middle
        title: Color Extraction by using colorgram for app "monde"
        link: github.com/ChanYeongShin
        # link_text: Project Website
        additional_links:
          - title:  ChanYeongShin/ChanYeongShin.github.io
            icon: fab fa-github
            url: github.com/ChanYeongShin/ChanYeongShin.github.io
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          test
        description: | # this will include new lines to allow paragraphs
          test
      - layout: top-middle
        title: MONDE-PERSIAN - Data Management & Staff Server for app "monde"
        link: github.com/ChanYeongShin
        # link_text: Project Website
        additional_links:
          - title:  ChanYeongShin/ChanYeongShin.github.io
            icon: fab fa-github
            url: github.com/ChanYeongShin/ChanYeongShin.github.io
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          test
        description: | # this will include new lines to allow paragraphs
          test
      - layout: top-middle
        title: Multi-Label Image Classification at Handbag for app "monde"
        link: github.com/ChanYeongShin
        # link_text: Project Website
        additional_links:
          - title:  ChanYeongShin/ChanYeongShin.github.io
            icon: fab fa-github
            url: github.com/ChanYeongShin/ChanYeongShin.github.io
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          test
        description: | # this will include new lines to allow paragraphs
          test
      - layout: top-middle
        title: Object Detection at Handbag for app "monde"
        link: github.com/ChanYeongShin
        # link_text: Project Website
        additional_links:
          - title:  ChanYeongShin/ChanYeongShin.github.io
            icon: fab fa-github
            url: github.com/ChanYeongShin/ChanYeongShin.github.io
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          test
        description: | # this will include new lines to allow paragraphs
          test
      - layout: top-middle
        title: Hangul-OCR by using attention/CTC loss
        link: Private code because of security
        # link_text: Project Website
        additional_links:
          - title:  ChanYeongShin github link
            icon: fab fa-github
            url: github.com/ChanYeongShin/
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Mathpresso Hangul OCR Project for replacing GoogleOCR API.
        description: | # this will include new lines to allow paragraphs 
          - asd
          - asd
      - layout: top-middle
        title: Computational Photography Project
        link: github.com/ChanYeongShin/IIT6028
        # link_text: Project Website
        additional_links:
          - title:  CP Project
            icon: fab fa-github
            url: github.com/ChanYeongShin/IIT6028
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          test
        description: | # this will include new lines to allow paragraphs
          test
     
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Mondeique
        link: github.com/mondeique
        # link_text: mondeique.com
        sub_title: Chief Technical Officer (CTO) 
        caption: July 2019 - Present
        quote: >
          3D human modeling + Clothes Generator Developer
        description: | # this will include new lines to allow paragraphs
          I'm currently working as a CTO for style tech startup 'Mondeique'. 'Mondeique' has vision to implement fitting rooms in mobile with extreme technology. 
          
          We received angel seed investment in July 2020 and I enjoy working with our company's talented people.
          
      - layout: left
        title: Mathpresso R&D 
        link: mathpresso.com
        # link_text: mondeique.com
        sub_title: OCR intern
        caption: January 2019 - May 2019
        quote: >
          Hangul OCR intern  
        description: | # this will include new lines to allow paragraphs
          I worked as an intern in Korean OCR at Mathpresso, a startup that created an application called "QandA," an educational platform that has become the world's No. 1 with huge 
          investment.
          
          In fact, the company proceeded from the beginning to the end of the process from preprocessing data to using it for learning. 
          It wasn't enough to replace Google API, but I've experienced the same performance.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: M.S Yonsei University
        caption: 2018 - Present
        sub_title: School of Integrated Technology 
        quote: >
          Computer Vision & Machine Learning LAB
        description: | # this will include new lines to allow paragraphs
          I am conducting research in the lab of Professor "Hyunjung Shim" at Yonsei University CVML Lab. 
          
          Currently, we are conducting a study on the 3D Clothes generator, including the size that can replace the Simulator, and we are reading the corresponding paper.
      - layout: left
        title: B.S Yonsei University
        caption: 2015 - 2017
        sub_title: School of Integrated Technology 
        quote: >
          5th, I graduated early at the age of 21.
        description: | # this will include new lines to allow paragraphs
          I graduated from Yonsei University's IT convergence engineering department and took courses in various subjects that I learn in engineering college. 
          I learned about various fields such as semiconductor process technology, communication, computer engineering, and signal processing. 
          
          As a graduation thesis, we conducted a study to find tumors in CT images using AI.
      - layout: left
        title: Incheon Science High School
        caption: 2013 - 2014
        sub_title: 20th
        quote: >
          I graduated early at the age of 18.
        description: | # this will include new lines to allow paragraphs
          I graduated from the 20th Incheon Science High School. My major was chemistry, and at that time, I wanted to go to a pharmacy.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
