# Site
repository: ChanYeongShin/ChanYeongShin.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Eren Shin
title: Mondeique CTO / M.S Candidate for School of Integrated Technology in Yonsei Univ
email: eren@mondeique.com
website: https://github.com/ChanYeongShin

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: 
github_username:  ChanYeongShin
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/me.jpeg
about_content: | # this will include new lines to allow paragraphs
  test

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/ChanYeongShin
        # link_text: Project Website
        additional_links:
          - title:  ChanYeongShin/ChanYeongShin.github.io
            icon: fab fa-github
            url: github.com/ChanYeongShin/ChanYeongShin.github.io
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Mondeique
        link: mondeique.com
        # link_text: mondeique.com
        sub_title: chief technical officer(CTO) 
        caption: July 2019 - Present
        quote: >
          test
        description: | # this will include new lines to allow paragraphs
          test

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Yonsei University
        caption: 2015 - 2017
        sub_title: School of Integrated Technology 
        quote: >
          test
        description: | # this will include new lines to allow paragraphs
          test

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      test
      ![Trees](/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
